upload:
    resource: "@UploadBundle/Controller/"
    type:     annotation
    prefix:   /

forms:
    resource: "@FormsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
